server:
  port: ${PORT:8761} # Indicate the default PORT where this service will be started
 
eureka:
  instance:
    hostname: eurekaserviceregistry
  client:
    registerWithEureka: false   #telling the server not to register himself in the service registry
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0    #wait time for subsequent sync
spring:     
  application:
    name: eurekaserviceregistry   #current service name to be used by the eureka server
#zipkin:
#  base:
#    url: http://localhost:9411/
 